version: "3"
services:
  recommend-server:
    build:
      context: .
    image: recommend-server
    ports:
      - "8000:8000"
    volumes:
      - .:/recommend-django
    command: python manage.py runserver 0.0.0.0:8000


volumes:
  recommend-django:
